# Azure build pipelines for Sysmon

resources:
  repositories:
  - repository: Sysmon
    type: github
    endpoint: sysinternals
    name: sysinternals/SysmonforLinux

trigger:
    branches:
      include:
        - release/*
        - main
      exclude:
        - dev/*
        - test/*
  
pr:
- main

stages:
 - stage: "Build"
   jobs:
    - job: "Build_Sysmon_Ubuntu_20_04"
      pool: 
        name: "SMARTSentinel Agent Build Pool"
        demands:
        - SYSINT_TOOL -equals sysmon   
        - SYSINT_DISTRIBUTION -equals ubuntu_20_04
        - SYSINT_ARCHITECTURE -equals x86_64
      steps:
      - checkout: Sysmon
        submodules: true

      - script: |
          wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt -y update
          sudo apt -y install sysinternalsebpf
        displayName: "Install Sysinternalsebpf dependency"

      - template: templates/build.yaml

      - script: |
          sudo apt -y remove sysinternalsebpf
        displayName: "Remove Sysinternalsebpf dependency"
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
